name: Publish

on: push

jobs:
  publish:
    name: Publish plugin in npm
    runs-on: ubuntu-latest
    steps:
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ $TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: yarn install

      - run: yarn lint

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ $NPM_ACCESS_TOKEN }}
